seo:
  site_name: The Beach House
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: '#141410' 
  medium-text_color: '#4c4e3d' 
  light-text_color: '#e7e4dd' 
  featured-text_color: '#840032' 
  dark_color: '#141410'
  medium_color: '#4c4e3d' 
  light_color: '#d2ccbf'
  v-light_color: '#e7e4dd'
  featured_color: '#CF5C36'

